apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-u0ed
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-u0ed
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-u0ed
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-u0ed
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-u0ed
    spec:
      containers:
      - image: quay.io/qijing/happy-path-xpgk-tenant/appstudio/dc-metro-map-u0ed@sha256:9d0ce9dab6ac3c1ead700a29d678f052652c88031b1a6718aa6b27aa4c43baca
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
